---
- name: ensure required packages are installed
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - avahi-daemon
    - avahi-utils
  tags:
    - mdns-repeater

- name: ensure the avahi reflector is enabled
  lineinfile:
    dest: /etc/avahi/avahi-daemon.conf
    regexp: '^#enable-reflector.*$'
    line: 'enable-reflector=yes'
  notify:
    - restart avahi-daemon
  tags:
    - mdns-repeater
