---
- name: ensure required packages are installed
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - avahi-daemon
    - avahi-utils
  tags:
    - mdns-repeater

- name: ensure the avahi reflector is enabled
  ini_file:
    path: /etc/avahi/avahi-daemon.conf
    section: reflector
    option: enable-reflector
    value: "yes"
    no_extra_spaces: yes
    backup: yes
  notify:
    - restart avahi-daemon
  tags:
    - mdns-repeater
