---
- import_tasks: variables.yml
- import_tasks: packages.yml
- import_tasks: configuration.yml

- meta: flush_handlers

- name: ensure the avahi daemon is running
  service:
    name: "{{ dubzland_mdns_repeater_avahi_daemon_name }}"
    state: started
