---
- name: enable avahi daemon
  service:
    name: "{{ dubzland_mdns_repeater_avahi_daemon_name }}"

- name: restart avahi daemon
  service:
    name: "{{ dubzland_mdns_repeater_avahi_daemon_name }}"
    state: restarted
